version: '4'
services:
  asukarobot:
    container_name: asuka
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_ID=$API_ID
      - API_HASH=$API_HASH
      - BOT_TOKEN=$BOT_TOKEN
      - OWNER_ID=$OWNER_ID
    restart: on-failure
